name: ci-test-docs-build

on:
  pull_request:
    branches: [ main ]

permissions:
  contents: read 
  pages: write 
  id-token: write 

concurrency: 
  group: "pages"
  cancel-in-progress: false 

jobs:
  build-docs:
    runs-on: ubuntu-latest
    timeout-minutes: 15 
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4 

      - name: Setup up Python 
        uses: actions/setup-python@v5 
        with:
          python-version: "3.12"

      - name: Install Sphinx 
        run: | 
          python -m pip install --upgrade pip 
          pip install sphinx sphinx-toolbox piccolo-theme 
          
      - name: Build the documentation 
        run: sphinx-build -b html docs/source/ docs/build/html 
